/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import interfaces.InterfaceCliente;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author arauj
 */
public class ManipularCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InserirCliente
     */
    String ip = "127.0.0.1";
    public ManipularCliente() {
        initComponents();
        txtID.setEditable(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtNascimento = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jcbHabilitarEdicao = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setResizable(false);
        setTitle("Manipular Clientes");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 150, 15, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 200, 41, 20);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel3.setText("Sexo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 200, 32, 20);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel4.setText("Data de Nascimento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 200, 140, 20);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel5.setText("Cidade");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 240, 48, 20);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel6.setText("Endereço");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 240, 64, 20);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel7.setText("Telefone");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 280, 59, 20);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 280, 37, 20);

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID);
        txtID.setBounds(30, 150, 60, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(55, 197, 115, 30);
        getContentPane().add(txtSexo);
        txtSexo.setBounds(264, 197, 88, 30);
        getContentPane().add(txtNascimento);
        txtNascimento.setBounds(514, 197, 132, 30);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(62, 237, 108, 30);
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(296, 237, 350, 30);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(73, 277, 97, 30);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(269, 277, 377, 30);

        jcbHabilitarEdicao.setText("Habilitar Edição/Exclusão");
        jcbHabilitarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHabilitarEdicaoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbHabilitarEdicao);
        jcbHabilitarEdicao.setBounds(100, 150, 200, 23);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 380, 130, 31);

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 380, 130, 31);

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 380, 130, 31);

        jButton4.setText("Listar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(480, 380, 130, 31);

        setBounds(0, 0, 670, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbHabilitarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHabilitarEdicaoActionPerformed
        if(jcbHabilitarEdicao.isSelected()){
           txtID.setEditable(true); 
        }else{
            txtID.setEditable(false);
            limparCampos();
        }
        
    }//GEN-LAST:event_jcbHabilitarEdicaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Registry conexao;
        try {
            conexao = LocateRegistry.getRegistry(ip,1100);
            InterfaceCliente clienteServico =(InterfaceCliente) conexao.lookup("cliente");
            Cliente c = new Cliente();
            c.setNome(txtNome.getText());
            c.setSexo(txtSexo.getText());
            c.setData_nasc(txtNascimento.getText());
            c.setCidade(txtCidade.getText());
            c.setEndereco(txtEndereco.getText());
            c.setTelefone(txtTelefone.getText());
            c.setEmail(txtEmail.getText());
            JOptionPane.showMessageDialog(this, clienteServico.inserirCliente(c));
            limparCampos();
            
        }catch (RemoteException erro){
            System.out.println("Erro de conexao com o servidor" + erro.getMessage());
        }catch(NotBoundException erro){
            System.out.println("Erro de conexao com o servidor" + erro.getMessage());
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ListaCliente listaCliente = new ListaCliente();
        getParent().add(listaCliente);
        listaCliente.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        if(!txtID.getText().equals("")){
            Registry conexao;
        try{
            conexao = LocateRegistry.getRegistry(ip,1100);
            InterfaceCliente clienteServico =(InterfaceCliente) conexao.lookup("cliente"); 
            int digitado = Integer.parseInt(txtID.getText());
            for(Cliente c: clienteServico.selecionarCliente(Integer.parseInt(txtID.getText()))){
                if(digitado == c.getId_cli()){
                    txtNome.setText(c.getNome());
                    txtSexo.setText(c.getSexo());
                    txtNascimento.setText(c.getData_nasc());
                    txtCidade.setText(c.getCidade());
                    txtEndereco.setText(c.getEndereco());
                    txtTelefone.setText(c.getTelefone());
                    txtEmail.setText(c.getEmail());
                }
            }
        }catch (RemoteException erro){
            System.out.println("Erro de conexao com o servidor : " + erro.getMessage());
        }catch(NotBoundException erro){
            System.out.println("Erro de conexao com o servidor : " + erro.getMessage());
        } 
        }
    }//GEN-LAST:event_txtIDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Registry conexao;
        try{
            conexao = LocateRegistry.getRegistry(ip,1100);
            InterfaceCliente clienteServico =(InterfaceCliente) conexao.lookup("cliente"); 
            JOptionPane.showMessageDialog(this, clienteServico.excluirCliente(Integer.parseInt(txtID.getText())));
            limparCampos();
        }catch (RemoteException erro){
            System.out.println("Erro de conexao com o servidor : " + erro.getMessage());
        }catch(NotBoundException erro){
            System.out.println("Erro de conexao com o servidor : " + erro.getMessage());
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Registry conexao;
        try {
            conexao = LocateRegistry.getRegistry(ip,1100);
            InterfaceCliente clienteServico =(InterfaceCliente) conexao.lookup("cliente");
            Cliente c = new Cliente();
            c.setId_cli(Integer.parseInt(txtID.getText()));
            c.setNome(txtNome.getText());
            c.setSexo(txtSexo.getText());
            c.setData_nasc(txtNascimento.getText());
            c.setCidade(txtCidade.getText());
            c.setEndereco(txtEndereco.getText());
            c.setTelefone(txtTelefone.getText());
            c.setEmail(txtEmail.getText());
            JOptionPane.showMessageDialog(this, clienteServico.editarCliente(c));
            limparCampos();
            
        }catch (RemoteException erro){
            System.out.println("Erro de conexao com o servidor" + erro.getMessage());
        }catch(NotBoundException erro){
            System.out.println("Erro de conexao com o servidor" + erro.getMessage());
        } 
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void limparCampos(){
        txtID.setText("");
        txtNome.setText("");
        txtSexo.setText("");
        txtNascimento.setText("");
        txtCidade.setText("");
        txtEndereco.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JCheckBox jcbHabilitarEdicao;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
