/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import interfaces.InterfaceFuncionario;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import model.Funcionario;

/**
 *
 * @author arauj
 */
public class ManipularFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManipularFuncionario
     */
    String ip = "127.0.0.1";
    public ManipularFuncionario() {
        initComponents();
        txtID.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jcbHabilitarEdicao = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        txtTurno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFuncao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 150, 15, 30);

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID);
        txtID.setBounds(30, 150, 60, 30);

        jcbHabilitarEdicao.setText("Habilitar Edição/Exclusão");
        jcbHabilitarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHabilitarEdicaoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbHabilitarEdicao);
        jcbHabilitarEdicao.setBounds(100, 150, 200, 23);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 200, 41, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(55, 197, 115, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel3.setText("Sexo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 200, 32, 20);
        getContentPane().add(txtSexo);
        txtSexo.setBounds(264, 197, 88, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel4.setText("Data de Nascimento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 200, 140, 20);
        getContentPane().add(txtNascimento);
        txtNascimento.setBounds(514, 197, 132, 30);
        getContentPane().add(txtTurno);
        txtTurno.setBounds(62, 237, 108, 30);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel5.setText("Turno");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 240, 41, 20);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel6.setText("Função");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 240, 50, 20);
        getContentPane().add(txtFuncao);
        txtFuncao.setBounds(296, 237, 350, 30);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel7.setText("Telefone");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 280, 59, 20);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(73, 277, 97, 30);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 280, 37, 20);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(269, 277, 377, 30);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 380, 130, 31);

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 380, 130, 31);

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 380, 130, 31);

        jButton4.setText("Listar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(480, 380, 130, 31);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel9.setText("Salario");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 320, 47, 20);
        getContentPane().add(txtSalario);
        txtSalario.setBounds(70, 320, 100, 30);

        setBounds(0, 0, 670, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        if(!txtID.getText().equals("")){
            Registry conexao;
            try{
                conexao = LocateRegistry.getRegistry(ip,1100);
                InterfaceFuncionario funcionarioServico =(InterfaceFuncionario) conexao.lookup("funcionario");
                int digitado = Integer.parseInt(txtID.getText());
                for(Funcionario f: funcionarioServico.selecionarFuncionario(Integer.parseInt(txtID.getText()))){
                    if(digitado == f.getId_fun()){
                        txtNome.setText(f.getNome());
                        txtSexo.setText(f.getSexo());
                        txtNascimento.setText(f.getData_nasc());
                        txtTurno.setText(f.getTurno());
                        txtFuncao.setText(f.getFuncao());
                        txtTelefone.setText(f.getTelefone());
                        txtEmail.setText(f.getEmail());
                        txtSalario.setText(String.valueOf(f.getSalario()));
                    }
                }
            }catch (RemoteException erro){
                System.out.println("Erro de conexao com o servidor : " + erro.getMessage());
            }catch(NotBoundException erro){
                System.out.println("Erro de conexao com o servidor : " + erro.getMessage());
            }
        }
    }//GEN-LAST:event_txtIDActionPerformed

    private void jcbHabilitarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHabilitarEdicaoActionPerformed
        if(jcbHabilitarEdicao.isSelected()){
            txtID.setEditable(true);
        }else{
            txtID.setEditable(false);
            limparCampos();
        }

    }//GEN-LAST:event_jcbHabilitarEdicaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Registry conexao;
        try {
            conexao = LocateRegistry.getRegistry(ip,1100);
            InterfaceFuncionario funcionarioServico =(InterfaceFuncionario) conexao.lookup("funcionario");
            Funcionario f = new Funcionario();
            f.setNome(txtNome.getText());
            f.setSexo(txtSexo.getText());
            f.setData_nasc(txtNascimento.getText());
            f.setSalario(Float.parseFloat(txtSalario.getText()));
            f.setTurno(txtTurno.getText());
            f.setFuncao(txtFuncao.getText());
            f.setTelefone(txtTelefone.getText());
            f.setEmail(txtEmail.getText());
            JOptionPane.showMessageDialog(this, funcionarioServico.inserirFuncionario(f));
            limparCampos();

        }catch (RemoteException erro){
            System.out.println("Erro de conexao com o servidor" + erro.getMessage());
        }catch(NotBoundException erro){
            System.out.println("Erro de conexao com o servidor" + erro.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Registry conexao;
        try {
            conexao = LocateRegistry.getRegistry(ip,1100);
            InterfaceFuncionario funcionarioServico =(InterfaceFuncionario) conexao.lookup("funcionario");
            Funcionario f = new Funcionario();
            f.setId_fun(Integer.parseInt(txtID.getText()));
            f.setNome(txtNome.getText());
            f.setSexo(txtSexo.getText());
            f.setData_nasc(txtNascimento.getText());
            f.setSalario(Float.parseFloat(txtSalario.getText()));
            f.setTurno(txtTurno.getText());
            f.setFuncao(txtFuncao.getText());
            f.setTelefone(txtTelefone.getText());
            f.setEmail(txtEmail.getText());
            JOptionPane.showMessageDialog(this, funcionarioServico.editarFuncionario(f));
            limparCampos();

        }catch (RemoteException erro){
            System.out.println("Erro de conexao com o servidor" + erro.getMessage());
        }catch(NotBoundException erro){
            System.out.println("Erro de conexao com o servidor" + erro.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Registry conexao;
        try{
            conexao = LocateRegistry.getRegistry(ip,1100);
            InterfaceFuncionario funcionarioServico =(InterfaceFuncionario) conexao.lookup("funcionario");
            JOptionPane.showMessageDialog(this, funcionarioServico.excluirFuncionario(Integer.parseInt(txtID.getText())));
            limparCampos();
        }catch (RemoteException erro){
            System.out.println("Erro de conexao com o servidor : " + erro.getMessage());
        }catch(NotBoundException erro){
            System.out.println("Erro de conexao com o servidor : " + erro.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ListaFuncionario listaFuncionario = new ListaFuncionario();
        getParent().add(listaFuncionario);
        listaFuncionario.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    public void limparCampos(){
        txtID.setText("");
        txtNome.setText("");
        txtSexo.setText("");
        txtNascimento.setText("");
        txtTurno.setText("");
        txtFuncao.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtSalario.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox jcbHabilitarEdicao;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFuncao;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
